<a href="https://colab.research.google.com/github/hazarali/Pandas-Notlari/blob/main/pandas_notlar%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [1]:
import pandas as pd
import numpy as np

In [2]:
a=1
for i in dir(pd):
  if a%5==0:
    print()
  a=a+1  
  print(i, end= " ")
  

BooleanDtype Categorical CategoricalDtype CategoricalIndex 
DataFrame DateOffset DatetimeIndex DatetimeTZDtype ExcelFile 
ExcelWriter Flags Float32Dtype Float64Dtype Float64Index 
Grouper HDFStore Index IndexSlice Int16Dtype 
Int32Dtype Int64Dtype Int64Index Int8Dtype Interval 
IntervalDtype IntervalIndex MultiIndex NA NaT 
NamedAgg Period PeriodDtype PeriodIndex RangeIndex 
Series SparseDtype StringDtype Timedelta TimedeltaIndex 
Timestamp UInt16Dtype UInt32Dtype UInt64Dtype UInt64Index 
UInt8Dtype __builtins__ __cached__ __doc__ __docformat__ 
__file__ __getattr__ __git_version__ __loader__ __name__ 
__package__ __path__ __spec__ __version__ _config 
_hashtable _is_numpy_dev _lib _libs _np_version_under1p18 
_testing _tslib _typing _version api 
array arrays bdate_range compat concat 
core crosstab cut date_range describe_option 
errors eval factorize get_dummies get_option 
infer_freq interval_range io isna isnull 
json_normalize lreshape melt merge merge_asof 
merge_ordered notna n

In [ ]:
a=pd.Series([1,2,3,4,5])

In [ ]:
seri=pd.Series(["at","muz"])

In [ ]:
seri

0     at
1    muz
dtype: object

In [ ]:
listem=[1,2,3,4,5,6]
pd.Series(listem)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
a=np.arange(53,56)

In [ ]:
seri=pd.Series(a)

In [ ]:
type(seri)

pandas.core.series.Series

In [ ]:
seri.size

3

In [ ]:
seri.shape

(3,)

In [ ]:
seri.ndim

1

In [ ]:
seri.values

array([53, 54, 55])

In [ ]:
seri.head()

0    53
1    54
2    55
dtype: int64

In [ ]:
pd.value_counts(seri)

53    1
54    1
55    1
dtype: int64

In [ ]:
seri=pd.Series([123,234,566,123,543,134,54,6,2,56,35,73,234,656,74,3323,])

In [ ]:
pd.value_counts(seri)

123     2
234     2
566     1
543     1
134     1
54      1
6       1
2       1
56      1
35      1
73      1
656     1
74      1
3323    1
dtype: int64

In [ ]:
deger=pd.unique(seri)

In [ ]:
type(deger)

numpy.ndarray

In [ ]:
a=np.random.randint(2,20,4)
print(a)

[11 13  8 13]


In [ ]:
seri=pd.Series(a)

In [ ]:
seri

0    11
1    13
2     8
3    13
dtype: int64

In [ ]:
seri.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
seri.index=["a","b","c","d"]

In [ ]:
seri

a    11
b    13
c     8
d    13
dtype: int64

In [ ]:
seri.a

11

In [ ]:
seri.b

13

In [ ]:
seri[2]      ## index mantığı hala çalşıyor ama indexleri int verirsek çalışmaz

8

In [ ]:
sozluk={"a":[45,56],"b":[12,34],"c":[23,45]}

In [ ]:
pd.Series(sozluk)

a    [45, 56]
b    [12, 34]
c    [23, 45]
dtype: object

In [ ]:
seri.values

array([11, 13,  8, 13])

In [ ]:
seri.items()

In [ ]:
seri.item

<bound method IndexOpsMixin.item of a    11
b    13
c     8
d    13
dtype: int64>

In [ ]:
seri.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
seri[1:4]

b    13
c     8
d    13
dtype: int64

In [ ]:
#iloc ve loc kullanımın nedeni indexleriler ile slice yapmak için

In [ ]:
listem=[]
for i in "abcdefghjklm":
  listem.append(i)

In [ ]:
len(listem)

12

In [ ]:
a=np.random.randint(10,30,12)

In [ ]:
serie=pd.Series(a,index=listem)

In [ ]:
serie

a    28
b    24
c    18
d    18
e    29
f    29
g    11
h    17
j    27
k    16
l    10
m    10
dtype: int64

In [ ]:
serie.head()

a    28
b    24
c    18
d    18
e    29
dtype: int64

In [ ]:
serie.loc["d"]                                # lock index ismiylee ulaşmayı sağlar. index adını kullanmalısın

18

In [ ]:
serie.iloc[3]                                #iloc index sıralaması ile ulaşmayı sağlar iloca index ismiyle yazsan hata alırsın

18

In [ ]:
serie.loc["e":"j"]

e    29
f    29
g    11
h    17
j    27
dtype: int64

In [ ]:
serie.loc["e":"j"].values

array([29, 29, 11, 17, 27])

In [ ]:
a=serie.loc["e":"j"]
print(type(a))

<class 'pandas.core.series.Series'>


In [ ]:
b=serie.loc["e":"j"].values
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
serie[4:9]

e    29
f    29
g    11
h    17
j    27
dtype: int64

In [ ]:
serie.iloc[4:9]

e    29
f    29
g    11
h    17
j    27
dtype: int64

In [ ]:
serie.loc[4:9]                   ##hata alırız çünkü loc kullanırken index ismiyle kullan

TypeError: ignored

In [ ]:
seri

a    11
b    13
c     8
d    13
dtype: int64

In [ ]:
pd.concat([seri,serie])

a    11
b    13
c     8
d    13
a    28
b    24
c    18
d    18
e    29
f    29
g    11
h    17
j    27
k    16
l    10
m    10
dtype: int64

In [ ]:
"a" in serie

True

In [ ]:
serie["a"]

28

In [ ]:
serie["a"]=67                                                                                 ## eleman değişimi yapabiliriz

In [ ]:
b=serie[25>serie]

In [ ]:
b

b    24
c    18
d    18
g    11
h    17
k    16
l    10
m    10
dtype: int64

In [ ]:
serie[(25>serie)]
#print(serie[(25>serie)].sum()
#print(serie)

b    24
c    18
d    18
g    11
h    17
k    16
l    10
m    10
dtype: int64

In [ ]:
serie>23

a     True
b     True
c    False
d    False
e     True
f     True
g    False
h    False
j     True
k    False
l    False
m    False
dtype: bool

In [ ]:
serie1=serie+5

In [ ]:
serie1

a    72
b    29
c    23
d    23
e    34
f    34
g    16
h    22
j    32
k    21
l    15
m    15
dtype: int64

In [ ]:
serie3=seri+serie

In [ ]:
serie3                         # iki serinin toplanması için aynı index no olması gereklidir. Aynı değer olmayanlar için NAN DEĞERİ OLUR

a    78.0
b    37.0
c    26.0
d    31.0
e     NaN
f     NaN
g     NaN
h     NaN
j     NaN
k     NaN
l     NaN
m     NaN
dtype: float64

In [ ]:
seri

a    11
b    13
c     8
d    13
dtype: int64

In [ ]:
serie.describe()

count    12.0000
mean     23.0000
std      15.4978
min      10.0000
25%      14.7500
50%      18.0000
75%      27.5000
max      67.0000
dtype: float64

In [ ]:
sorted(serie)

[10, 10, 11, 16, 17, 18, 18, 24, 27, 29, 29, 67]

In [ ]:
my_nump=np.random.randint(10,40,(3,3))
data=pd.DataFrame((my_nump))

In [ ]:
data

0   1   2
0  21  39  29
1  18  24  33
2  32  25  18

In [ ]:
data.index=(["isim","yaş","cinsiyet"])

In [ ]:
data

0   1   2
isim      21  39  29
yaş       18  24  33
cinsiyet  32  25  18

In [ ]:
data.columns=["a","b","c"]

In [ ]:
data

a   b   c
isim      21  39  29
yaş       18  24  33
cinsiyet  32  25  18

In [ ]:
data.axes

[Index(['isim', 'yaş', 'cinsiyet'], dtype='object'),
 Index(['a', 'b', 'c'], dtype='object')]

In [ ]:
data.ndim

2

In [ ]:
data.shape

(3, 3)

In [ ]:
data.describe()

a          b          c
count   3.000000   3.000000   3.000000
mean   23.666667  29.333333  26.666667
std     7.371115   8.386497   7.767453
min    18.000000  24.000000  18.000000
25%    19.500000  24.500000  23.500000
50%    21.000000  25.000000  29.000000
75%    26.500000  32.000000  31.000000
max    32.000000  39.000000  33.000000

In [ ]:
listem1=[4,5,634,245,234,52,123,]
data1=pd.DataFrame(listem1)

In [ ]:
data1

0
0    4
1    5
2  634
3  245
4  234
5   52
6  123

In [ ]:
sozluk1={"a":[3,4,5,3],"b":[3,4,5]}

In [ ]:
data2=pd.DataFrame(sozluk1)

ValueError: ignored

In [ ]:
sozluk1={"a":[3,4,5,3],"b":[3,4,5,3]}

In [ ]:
data2=pd.DataFrame(sozluk1)

In [ ]:
data2

a  b
0  3  3
1  4  4
2  5  5
3  3  3

In [ ]:
a=np.random.randint(10,20,6)
b=np.random.randint(20,30,6)
c=np.random.randint(30,40,6)
sozluk2={"a":a,"b":b,"c":c}

In [ ]:
datam=pd.DataFrame(sozluk2)

In [ ]:
datam

a   b   c
0  15  26  38
1  16  22  32
2  16  29  39
3  18  23  32
4  10  23  34
5  18  21  33

In [ ]:
datam[1:3,2:4]                                   # iloc yada loc kullan

TypeError: ignored

In [ ]:
datam.iloc[0:4]

a   b   c
0  15  26  38
1  16  22  32
2  16  29  39
3  18  23  32

In [ ]:
datam.index=["a","b","c","d","e","f"]

In [ ]:
datam

a   b   c
a  15  26  38
b  16  22  32
c  16  29  39
d  18  23  32
e  10  23  34
f  18  21  33

In [ ]:
datam.columns=["ali","hasan","veli"]

In [ ]:
datam

ali  hasan  veli
a   15     26    38
b   16     22    32
c   16     29    39
d   18     23    32
e   10     23    34
f   18     21    33

In [ ]:
datam.iloc["a":"d"]                               ##isim vermek istiyorsan loc kullanırsın

TypeError: ignored

In [ ]:
datam.loc["a":"d"]

ali  hasan  veli
a   15     26    38
b   16     22    32
c   16     29    39
d   18     23    32

In [ ]:
datam.loc["d"]                                          #type pd dir

ali      18
hasan    23
veli     32
Name: d, dtype: int64

In [ ]:
datam.loc["d"].values                                 #type numpy dir

array([18, 23, 32])

In [ ]:
datam.iloc[3]

ali      18
hasan    23
veli     32
Name: d, dtype: int64

In [ ]:
datam.loc["d"][1] 

23

In [ ]:
datam.loc["a":"c"]

ali  hasan  veli
a   15     26    38
b   16     22    32
c   16     29    39

In [ ]:
datam.loc["a":"c"][0:1]

ali  hasan  veli
a   15     26    38

In [ ]:
datam.loc["a":"c"][2:4]

ali  hasan  veli
c   16     29    39

In [ ]:
datam.loc["a":"c"]

ali  hasan  veli
a   15     26    38
b   16     22    32
c   16     29    39

In [ ]:
data.drop(["a"])

KeyError: ignored

In [ ]:
datam.drop("a",axis=0)

ali  hasan  veli
b   16     22    32
c   16     29    39
d   18     23    32
e   10     23    34
f   18     21    33

In [ ]:
datam.drop("a",axis=1)

KeyError: ignored

In [ ]:
data

a   b   c
isim      39  23  31
yaş       21  18  19
cinsiyet  16  37  38

In [ ]:
data.drop("a",axis=0)

KeyError: ignored

In [ ]:
data.drop("a",axis=1)                             # column silmek için axis=1 değeri ver ve column ismini yaz

b   c
isim      23  31
yaş       18  19
cinsiyet  37  38

In [ ]:
datam

ali  hasan  veli
a   15     26    38
b   16     22    32
c   16     29    39
d   18     23    32
e   10     23    34
f   18     21    33

In [ ]:
datam.drop("ali",axis=1)

hasan  veli
a     26    38
b     22    32
c     29    39
d     23    32
e     23    34
f     21    33

In [ ]:
datam.drop(["d","f"],axis=0)                          #satır silmek için satır ismini yaz axis=0 ver

ali  hasan  veli
a   15     26    38
b   16     22    32
c   16     29    39
e   10     23    34

In [ ]:
datam.hasan

a    26
b    22
c    29
d    23
e    23
f    21
Name: hasan, dtype: int64

In [ ]:
datam["hasan"]

a    26
b    22
c    29
d    23
e    23
f    21
Name: hasan, dtype: int64

In [ ]:
datam["ali","hasan"]

KeyError: ignored

In [ ]:
datam[["ali","hasan"]]

ali  hasan
a   15     26
b   16     22
c   16     29
d   18     23
e   10     23
f   18     21

In [ ]:
datam["yeni_colum"]=1,2,3,4,5,6

In [ ]:
datam

ali  hasan  veli  yeni_colum
a   15     26    38           1
b   16     22    32           2
c   16     29    39           3
d   18     23    32           4
e   10     23    34           5
f   18     21    33           6

In [ ]:
datam["yeni_column"]=[13,12,20,4,5,3]

In [ ]:
datam

ali  hasan  veli  yeni_colum  yeni_column
a   15     26    38           1           13
b   16     22    32           2           12
c   16     29    39           3           20
d   18     23    32           4            4
e   10     23    34           5            5
f   18     21    33           6            3

In [ ]:
d=np.arange(21,64,8)

In [ ]:
d

array([21, 29, 37, 45, 53, 61])

In [ ]:
datam["new_column"]=d

In [ ]:
datam

ali  hasan  veli  yeni_colum  yeni_column  new_column
a   15     26    38           1           13          21
b   16     22    32           2           12          29
c   16     29    39           3           20          37
d   18     23    32           4            4          45
e   10     23    34           5            5          53
f   18     21    33           6            3          61

In [ ]:
datam["carpılmış_sutun"]=datam["ali"]*datam["veli"]

In [ ]:
datam

ali  hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun
a   15     26    38           1           13          21              570
b   16     22    32           2           12          29              512
c   16     29    39           3           20          37              624
d   18     23    32           4            4          45              576
e   10     23    34           5            5          53              340
f   18     21    33           6            3          61              594

In [ ]:
datam.describe()

ali      hasan       veli  yeni_colum  yeni_column  new_column  \
count   6.000000   6.000000   6.000000    6.000000     6.000000     6.00000   
mean   15.500000  24.000000  34.666667    3.500000     9.500000    41.00000   
std     2.949576   2.966479   3.076795    1.870829     6.655825    14.96663   
min    10.000000  21.000000  32.000000    1.000000     3.000000    21.00000   
25%    15.250000  22.250000  32.250000    2.250000     4.250000    31.00000   
50%    16.000000  23.000000  33.500000    3.500000     8.500000    41.00000   
75%    17.500000  25.250000  37.000000    4.750000    12.750000    51.00000   
max    18.000000  29.000000  39.000000    6.000000    20.000000    61.00000   

       carpılmış_sutun  
count         6.000000  
mean        536.000000  
std         102.816341  
min         340.000000  
25%         526.500000  
50%         573.000000  
75%         589.500000  
max         624.000000

In [ ]:
my_deger=datam.describe

In [ ]:
datam.describe().loc["mean"]

ali                 15.500000
hasan               24.000000
veli                34.666667
yeni_colum           3.500000
yeni_column          9.500000
new_column          41.000000
carpılmış_sutun    536.000000
Name: mean, dtype: float64

In [ ]:
datam.describe().loc["mean"].values

array([ 15.5       ,  24.        ,  34.66666667,   3.5       ,
         9.5       ,  41.        , 536.        ])

In [ ]:
datam[0:3]

ali  hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun
a   15     26    38           1           13          21              570
b   16     22    32           2           12          29              512
c   16     29    39           3           20          37              624

In [ ]:
data.iloc[1:3,0:5]

a   b   c
yaş       21  18  19
cinsiyet  16  37  38

In [ ]:
datam

ali  hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun
a   15     26    38           1           13          21              570
b   16     22    32           2           12          29              512
c   16     29    39           3           20          37              624
d   18     23    32           4            4          45              576
e   10     23    34           5            5          53              340
f   18     21    33           6            3          61              594

In [ ]:
datam.loc["a":"e","veli":"new_column"]                                 #loc ile son değerde hesaba katılır

veli  yeni_colum  yeni_column  new_column
a    38           1           13          21
b    32           2           12          29
c    39           3           20          37
d    32           4            4          45
e    34           5            5          53

In [ ]:
datam.loc["a":"e","veli":"new_column"]>14

veli  yeni_colum  yeni_column  new_column
a  True       False        False        True
b  True       False        False        True
c  True       False         True        True
d  True       False        False        True
e  True       False        False        True

In [ ]:
datam[datam.loc["a":"e","veli":"new_column"]<15]

ali  hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun
a  NaN    NaN   NaN         1.0         13.0         NaN              NaN
b  NaN    NaN   NaN         2.0         12.0         NaN              NaN
c  NaN    NaN   NaN         3.0          NaN         NaN              NaN
d  NaN    NaN   NaN         4.0          4.0         NaN              NaN
e  NaN    NaN   NaN         5.0          5.0         NaN              NaN
f  NaN    NaN   NaN         NaN          NaN         NaN              NaN

In [ ]:
datam

ali  hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun
a   15     26    38           1           13          21              570
b   16     22    32           2           12          29              512
c   16     29    39           3           20          37              624
d   18     23    32           4            4          45              576
e   10     23    34           5            5          53              340
f   18     21    33           6            3          61              594

In [ ]:
datam[datam.ali<16] 

ali  hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun
a   15     26    38           1           13          21              570
e   10     23    34           5            5          53              340

In [ ]:
datam[datam.ali<16]["new_column"]                             #sadece newe_columdekilerini görelim

a    21
e    53
Name: new_column, dtype: int64

In [ ]:
veri=datam[datam.loc["a":"e","veli":"new_column"]<15]

In [ ]:
veri

ali  hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun
a  NaN    NaN   NaN         1.0         13.0         NaN              NaN
b  NaN    NaN   NaN         2.0         12.0         NaN              NaN
c  NaN    NaN   NaN         3.0          NaN         NaN              NaN
d  NaN    NaN   NaN         4.0          4.0         NaN              NaN
e  NaN    NaN   NaN         5.0          5.0         NaN              NaN
f  NaN    NaN   NaN         NaN          NaN         NaN              NaN

In [ ]:
veri.fillna(value=0)

ali  hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun
a  0.0    0.0   0.0         1.0         13.0         0.0              0.0
b  0.0    0.0   0.0         2.0         12.0         0.0              0.0
c  0.0    0.0   0.0         3.0          0.0         0.0              0.0
d  0.0    0.0   0.0         4.0          4.0         0.0              0.0
e  0.0    0.0   0.0         5.0          5.0         0.0              0.0
f  0.0    0.0   0.0         0.0          0.0         0.0              0.0

In [ ]:
veri.sum()

ali                 0.0
hasan               0.0
veli                0.0
yeni_colum         15.0
yeni_column        34.0
new_column          0.0
carpılmış_sutun     0.0
dtype: float64

In [ ]:
veri

ali  hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun
a  NaN    NaN   NaN         1.0         13.0         NaN              NaN
b  NaN    NaN   NaN         2.0         12.0         NaN              NaN
c  NaN    NaN   NaN         3.0          NaN         NaN              NaN
d  NaN    NaN   NaN         4.0          4.0         NaN              NaN
e  NaN    NaN   NaN         5.0          5.0         NaN              NaN
f  NaN    NaN   NaN         NaN          NaN         NaN              NaN

In [ ]:
veri.sum().sum()

49.0

In [ ]:
ort=veri.sum().sum()/veri.size()

TypeError: ignored

In [ ]:
ort=veri.sum().sum()/veri.size

In [ ]:
ort

1.1666666666666667

In [ ]:
veri.isnull()

ali  hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun
a  True   True  True       False        False        True             True
b  True   True  True       False        False        True             True
c  True   True  True       False         True        True             True
d  True   True  True       False        False        True             True
e  True   True  True       False        False        True             True
f  True   True  True        True         True        True             True

In [ ]:
veri.isnull().sum()                                   # datamda ger bir columnda kaçtane nan değeri var onu verir

ali                6
hasan              6
veli               6
yeni_colum         1
yeni_column        2
new_column         6
carpılmış_sutun    6
dtype: int64

In [ ]:
veri.isnull().sum().sum()                            #data framde kaç tane nan değeri var onu veriri

33

In [ ]:
ortalama=veri.sum().sum()/ (veri.size-veri.isnull().sum().sum())               

In [ ]:
ortalama

5.444444444444445

In [ ]:
veri.fillna(value=ortalama)

ali     hasan      veli  yeni_colum  yeni_column  new_column  \
a  5.444444  5.444444  5.444444    1.000000    13.000000    5.444444   
b  5.444444  5.444444  5.444444    2.000000    12.000000    5.444444   
c  5.444444  5.444444  5.444444    3.000000     5.444444    5.444444   
d  5.444444  5.444444  5.444444    4.000000     4.000000    5.444444   
e  5.444444  5.444444  5.444444    5.000000     5.000000    5.444444   
f  5.444444  5.444444  5.444444    5.444444     5.444444    5.444444   

   carpılmış_sutun  
a         5.444444  
b         5.444444  
c         5.444444  
d         5.444444  
e         5.444444  
f         5.444444

In [ ]:
data

a   b   c
isim      39  23  31
yaş       21  18  19
cinsiyet  16  37  38

In [ ]:
data+10

a   b   c
isim      49  33  41
yaş       31  28  29
cinsiyet  26  47  48

In [ ]:
pd.concat(data,datam)

<ipython-input-162-eaaaecd72377>:1: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  pd.concat(data,datam)


TypeError: ignored

In [ ]:
data

a   b   c
isim      39  23  31
yaş       21  18  19
cinsiyet  16  37  38

In [ ]:
datam

ali  hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun
a   15     26    38           1           13          21              570
b   16     22    32           2           12          29              512
c   16     29    39           3           20          37              624
d   18     23    32           4            4          45              576
e   10     23    34           5            5          53              340
f   18     21    33           6            3          61              594

In [ ]:
pd.concat([data,datam])                          #köşieli parantezi unnumatma

a     b     c   ali  hasan  veli  yeni_colum  yeni_column  \
isim      39.0  23.0  31.0   NaN    NaN   NaN         NaN          NaN   
yaş       21.0  18.0  19.0   NaN    NaN   NaN         NaN          NaN   
cinsiyet  16.0  37.0  38.0   NaN    NaN   NaN         NaN          NaN   
a          NaN   NaN   NaN  15.0   26.0  38.0         1.0         13.0   
b          NaN   NaN   NaN  16.0   22.0  32.0         2.0         12.0   
c          NaN   NaN   NaN  16.0   29.0  39.0         3.0         20.0   
d          NaN   NaN   NaN  18.0   23.0  32.0         4.0          4.0   
e          NaN   NaN   NaN  10.0   23.0  34.0         5.0          5.0   
f          NaN   NaN   NaN  18.0   21.0  33.0         6.0          3.0   

          new_column  carpılmış_sutun  
isim             NaN              NaN  
yaş              NaN              NaN  
cinsiyet         NaN              NaN  
a               21.0            570.0  
b               29.0            512.0  
c               37.0            624.0  
d               45.0            576.0  
e               53.0            340.0  
f               61.0            594.0

In [ ]:
pd.concat([data,datam],axis=1)   

a     b     c   ali  hasan  veli  yeni_colum  yeni_column  \
isim      39.0  23.0  31.0   NaN    NaN   NaN         NaN          NaN   
yaş       21.0  18.0  19.0   NaN    NaN   NaN         NaN          NaN   
cinsiyet  16.0  37.0  38.0   NaN    NaN   NaN         NaN          NaN   
a          NaN   NaN   NaN  15.0   26.0  38.0         1.0         13.0   
b          NaN   NaN   NaN  16.0   22.0  32.0         2.0         12.0   
c          NaN   NaN   NaN  16.0   29.0  39.0         3.0         20.0   
d          NaN   NaN   NaN  18.0   23.0  32.0         4.0          4.0   
e          NaN   NaN   NaN  10.0   23.0  34.0         5.0          5.0   
f          NaN   NaN   NaN  18.0   21.0  33.0         6.0          3.0   

          new_column  carpılmış_sutun  
isim             NaN              NaN  
yaş              NaN              NaN  
cinsiyet         NaN              NaN  
a               21.0            570.0  
b               29.0            512.0  
c               37.0            624.0  
d               45.0            576.0  
e               53.0            340.0  
f               61.0            594.0

In [ ]:
pd.concat([data,datam],axis=0)                                #yan yana birleşitirme yapar

a     b     c   ali  hasan  veli  yeni_colum  yeni_column  \
isim      39.0  23.0  31.0   NaN    NaN   NaN         NaN          NaN   
yaş       21.0  18.0  19.0   NaN    NaN   NaN         NaN          NaN   
cinsiyet  16.0  37.0  38.0   NaN    NaN   NaN         NaN          NaN   
a          NaN   NaN   NaN  15.0   26.0  38.0         1.0         13.0   
b          NaN   NaN   NaN  16.0   22.0  32.0         2.0         12.0   
c          NaN   NaN   NaN  16.0   29.0  39.0         3.0         20.0   
d          NaN   NaN   NaN  18.0   23.0  32.0         4.0          4.0   
e          NaN   NaN   NaN  10.0   23.0  34.0         5.0          5.0   
f          NaN   NaN   NaN  18.0   21.0  33.0         6.0          3.0   

          new_column  carpılmış_sutun  
isim             NaN              NaN  
yaş              NaN              NaN  
cinsiyet         NaN              NaN  
a               21.0            570.0  
b               29.0            512.0  
c               37.0            624.0  
d               45.0            576.0  
e               53.0            340.0  
f               61.0            594.0

In [ ]:
pd.concat([data,datam],ignore_index=0)   

a     b     c   ali  hasan  veli  yeni_colum  yeni_column  \
isim      39.0  23.0  31.0   NaN    NaN   NaN         NaN          NaN   
yaş       21.0  18.0  19.0   NaN    NaN   NaN         NaN          NaN   
cinsiyet  16.0  37.0  38.0   NaN    NaN   NaN         NaN          NaN   
a          NaN   NaN   NaN  15.0   26.0  38.0         1.0         13.0   
b          NaN   NaN   NaN  16.0   22.0  32.0         2.0         12.0   
c          NaN   NaN   NaN  16.0   29.0  39.0         3.0         20.0   
d          NaN   NaN   NaN  18.0   23.0  32.0         4.0          4.0   
e          NaN   NaN   NaN  10.0   23.0  34.0         5.0          5.0   
f          NaN   NaN   NaN  18.0   21.0  33.0         6.0          3.0   

          new_column  carpılmış_sutun  
isim             NaN              NaN  
yaş              NaN              NaN  
cinsiyet         NaN              NaN  
a               21.0            570.0  
b               29.0            512.0  
c               37.0            624.0  
d               45.0            576.0  
e               53.0            340.0  
f               61.0            594.0

In [ ]:
pd.concat([data,datam],ignore_index=1)   

a     b     c   ali  hasan  veli  yeni_colum  yeni_column  new_column  \
0  39.0  23.0  31.0   NaN    NaN   NaN         NaN          NaN         NaN   
1  21.0  18.0  19.0   NaN    NaN   NaN         NaN          NaN         NaN   
2  16.0  37.0  38.0   NaN    NaN   NaN         NaN          NaN         NaN   
3   NaN   NaN   NaN  15.0   26.0  38.0         1.0         13.0        21.0   
4   NaN   NaN   NaN  16.0   22.0  32.0         2.0         12.0        29.0   
5   NaN   NaN   NaN  16.0   29.0  39.0         3.0         20.0        37.0   
6   NaN   NaN   NaN  18.0   23.0  32.0         4.0          4.0        45.0   
7   NaN   NaN   NaN  10.0   23.0  34.0         5.0          5.0        53.0   
8   NaN   NaN   NaN  18.0   21.0  33.0         6.0          3.0        61.0   

   carpılmış_sutun  
0              NaN  
1              NaN  
2              NaN  
3            570.0  
4            512.0  
5            624.0  
6            576.0  
7            340.0  
8            594.0

In [ ]:
pd.concat([data,datam],ignore_index=True)   

a     b     c   ali  hasan  veli  yeni_colum  yeni_column  new_column  \
0  39.0  23.0  31.0   NaN    NaN   NaN         NaN          NaN         NaN   
1  21.0  18.0  19.0   NaN    NaN   NaN         NaN          NaN         NaN   
2  16.0  37.0  38.0   NaN    NaN   NaN         NaN          NaN         NaN   
3   NaN   NaN   NaN  15.0   26.0  38.0         1.0         13.0        21.0   
4   NaN   NaN   NaN  16.0   22.0  32.0         2.0         12.0        29.0   
5   NaN   NaN   NaN  16.0   29.0  39.0         3.0         20.0        37.0   
6   NaN   NaN   NaN  18.0   23.0  32.0         4.0          4.0        45.0   
7   NaN   NaN   NaN  10.0   23.0  34.0         5.0          5.0        53.0   
8   NaN   NaN   NaN  18.0   21.0  33.0         6.0          3.0        61.0   

   carpılmış_sutun  
0              NaN  
1              NaN  
2              NaN  
3            570.0  
4            512.0  
5            624.0  
6            576.0  
7            340.0  
8            594.0

In [ ]:
#boyutları aynı olmayanlar için join methodunu kullan

In [ ]:
toplanmıs=datam.join(data)

In [ ]:
toplanmıs

ali  hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun   a  \
a   15     26    38           1           13          21              570 NaN   
b   16     22    32           2           12          29              512 NaN   
c   16     29    39           3           20          37              624 NaN   
d   18     23    32           4            4          45              576 NaN   
e   10     23    34           5            5          53              340 NaN   
f   18     21    33           6            3          61              594 NaN   

    b   c  
a NaN NaN  
b NaN NaN  
c NaN NaN  
d NaN NaN  
e NaN NaN  
f NaN NaN

In [ ]:
data.join(datam)

a   b   c  ali  hasan  veli  yeni_colum  yeni_column  new_column  \
isim      39  23  31  NaN    NaN   NaN         NaN          NaN         NaN   
yaş       21  18  19  NaN    NaN   NaN         NaN          NaN         NaN   
cinsiyet  16  37  38  NaN    NaN   NaN         NaN          NaN         NaN   

          carpılmış_sutun  
isim                  NaN  
yaş                   NaN  
cinsiyet              NaN

In [ ]:
pd.merge(data,datam)

MergeError: ignored

In [ ]:
#  merge methodula datalardaki ortak değerler alınır

In [ ]:
data


a   b   c
isim      39  23  31
yaş       21  18  19
cinsiyet  16  37  38

In [ ]:
datam

ali  hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun
a   15     26    38           1           13          21              570
b   16     22    32           2           12          29              512
c   16     29    39           3           20          37              624
d   18     23    32           4            4          45              576
e   10     23    34           5            5          53              340
f   18     21    33           6            3          61              594

In [ ]:
datam["c"]=31,425,23,43,19,2

In [ ]:
datam

ali  hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun    c
a   15     26    38           1           13          21              570   31
b   16     22    32           2           12          29              512  425
c   16     29    39           3           20          37              624   23
d   18     23    32           4            4          45              576   43
e   10     23    34           5            5          53              340   19
f   18     21    33           6            3          61              594    2

In [ ]:
pd.merge(datam,data)

ali  hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun   c  \
0   15     26    38           1           13          21              570  31   
1   10     23    34           5            5          53              340  19   

    a   b  
0  39  23  
1  21  18

In [ ]:
datam.groupby("ali")

In [ ]:
datam.groupby("ali").sum()

hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun    c
ali                                                                        
10      23    34           5            5          53              340   19
15      26    38           1           13          21              570   31
16      51    71           5           32          66             1136  448
18      44    65          10            7         106             1170   45

In [ ]:
takımlar=pd.DataFrame({"takım":["GS","FB","GS","BJK","GS","FB","BJK"],"maas":[15000,30000,23433,43534,14434,32343,23300]})

In [ ]:
takımlar

takım   maas
0    GS  15000
1    FB  30000
2    GS  23433
3   BJK  43534
4    GS  14434
5    FB  32343
6   BJK  23300

In [ ]:
takımlar.groupby("takım")

In [ ]:
takımlar.groupby(["takım"])

In [ ]:
takımlar.groupby("takım").sum()

maas
takım       
BJK    66834
FB     62343
GS     52867

In [ ]:
takımlar.groupby("takım").sum().sum()

maas    182044
dtype: int64

In [ ]:
takımlar.groupby("takım").sum().loc["FB"]

maas    62343
Name: FB, dtype: int64

In [ ]:
takımlar.groupby("takım").sum().count()

maas    3
dtype: int64

In [ ]:
takımlar.groupby("takım").count()

maas
takım      
BJK       2
FB        2
GS        3

In [ ]:
takımlar.groupby("takım").min()                               #en düşük değerleini verir

maas
takım       
BJK    23300
FB     30000
GS     14434

In [ ]:
datam["veli"].unique()

array([38, 32, 39, 34, 33])

In [ ]:
datam["veli"].nunique()

5

In [ ]:
datam["veli"].value_counts()

32    2
38    1
39    1
34    1
33    1
Name: veli, dtype: int64

In [ ]:
datam

ali  hasan  veli  yeni_colum  yeni_column  new_column  carpılmış_sutun    c
a   15     26    38           1           13          21              570   31
b   16     22    32           2           12          29              512  425
c   16     29    39           3           20          37              624   23
d   18     23    32           4            4          45              576   43
e   10     23    34           5            5          53              340   19
f   18     21    33           6            3          61              594    2

In [ ]:
datam.pivot_table(index="ali",columns="veli",values="c")

veli     32   33    34    38    39
ali                               
10      NaN  NaN  19.0   NaN   NaN
15      NaN  NaN   NaN  31.0   NaN
16    425.0  NaN   NaN   NaN  23.0
18     43.0  2.0   NaN   NaN   NaN

In [ ]:
takımlar.groupby("takım").aggregate(["min",np.median,max])

maas                
         min   median    max
takım                       
BJK    23300  33417.0  43534
FB     30000  31171.5  32343
GS     14434  15000.0  23433